\ProvidesClass{enpc-article}[05/12/2016 KI Clubinfo des Ponts]
\LoadClass[11pt]{article}

\RequirePackage[frenchb]{babel}
\RequirePackage[utf8]{inputenc}
\RequirePackage[T1]{fontenc}
\RequirePackage{charter}

\RequirePackage{graphicx}
\RequirePackage{amsfonts}
\RequirePackage{amsmath}
\RequirePackage{amsthm}
\RequirePackage[a4paper,margin=1in]{geometry}

\RequirePackage{float}
\RequirePackage{empheq}

\RequirePackage{textcomp}

\RequirePackage{booktabs}

\RequirePackage{url}

\RequirePackage{mathtools}
\RequirePackage{tikz,tkz-tab}

\setlength{\parindent}{0em}
\setlength{\parskip}{0.5em}

\newcommand{\abs}[1]{\left\lvert#1\right\rvert}
\newcommand{\norm}[1]{\left\lVert#1\right\rVert}

\RequirePackage{hyperref}
